# SPDX-License-Identifier: 0BSD

name: FreeBSD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  FreeBSD-test:
    runs-on: ubuntu-latest
    name: Test xz on FreeBSD
    steps:
    - uses: actions/checkout@v4.1.6
    - name: Test in FreeBSD
      id: test
      uses: vmactions/FreeBSD-vm@d7b8fcc7711aa41ad45e8d9b737cf90f035a7e3d #v1.1.3
      with:
        usesh: true
        prepare: |
         pkg install -y autoconf automake gmake gettext-tools gtar libtool m4 po4a
        run: |
          set -e
          export LC_ALL=C LANG=C

          printf "Dumping system information\n"
          for cmd in 'freebsd-version' 'cat /etc/release' 'uname -a' 'cc --version' \
            'gcc --version' 'clang --version' 'ld --version' \
            'autoconf --version' 'automake --version' 'libtool --version' \
            'gettext --version' 'm4 --version' \
            'sed --version' 'awk --version' ; do
            printf "Running cmd: %s\n" ${cmd}
            ${cmd} || true
          done
          printf "\n\n"

          ./autogen.sh
          ./configure --enable-werror
          make
          make check VERBOSE=1
